### ISSUE TITLE
Can't manage to run the application

### ISSUE THREAD

**Issue by dydboy** [admxxi/smartbox#1]
I'm running the app from a docker container, I'm getting this after followign the steps and installing bower and npm dependences, what am I missing ?

```
node@e9ba3e9183e9:/myapp$ ember server
version: 1.13.15
Livereload server on http://localhost:49152
Serving on http://localhost:4200/
ENOENT: no such file or directory, stat '/myapp/tmp/concat_with_maps-input_base_path-npaQ2RE3.tmp/0/bower_components/foundation-sites/dist/js/foundation.js'
Error: ENOENT: no such file or directory, stat '/myapp/tmp/concat_with_maps-input_base_path-npaQ2RE3.tmp/0/bower_components/foundation-sites/dist/js/foundation.js'
  at Error (native)
  at Object.fs.statSync (fs.js:844:18)
  at ConcatWithMaps.keyForFile (/myapp/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/index.js:87:20)
  at Array.map (native)
  at ConcatWithMaps.CachingWriter._conditionalBuild (/myapp/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/index.js:109:65)
  at /myapp/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/read_compat.js:61:34
  at tryCatch (/myapp/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:538:12)
  at invokeCallback (/myapp/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:553:13)
  at publish (/myapp/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:521:7)
  at flush (/myapp/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:2373:5)
  at nextTickCallbackWith0Args (node.js:436:9)
  at process._tickCallback (node.js:365:13)

```

**Comment by admxxi** [comment]
Hi Fabio, this issue was fixed, please update/clone the branch again.
Please make sure you are using Node 0.12.12 before run the npm install and bower install and then:

`ember s
open http://localhost:4200/#/networks/index/`

Thanks.
